// examples/vue-standard/src/components/theme-toggle.vue
<script setup lang="ts">
import { ref, watchEffect, onMounted, onUnmounted } from "vue";

const matchMedia = window.matchMedia("(prefers-color-scheme: dark)");

defineProps<{ message: string }>();

const isDarkMode = ref(matchMedia.matches);

function handleChange(event: MediaQueryListEvent) {
  isDarkMode.value = event.matches;
}

onMounted(() => matchMedia.addEventListener("change", handleChange));
onUnmounted(() => matchMedia.removeEventListener("change", handleChange));

watchEffect(() => {
  isDarkMode.value
    ? document.body.classList.add("dark-scheme")
    : document.body.classList.remove("dark-scheme");
});
</script>

<template>
  <div class="centered">
    <div>
      <img
        class="logo"
        src="logo.svg"
        role="button"
        alt=""
        @click="isDarkMode = !isDarkMode"
      />
    </div>
    <h1>Vue</h1>
    <p>{{ message }}</p>
  </div>
</template>

<style scoped>
img {
  transition: all 0.4s ease;
}
.logo {
  will-change: filter;
}

.logo:hover {
  filter: drop-shadow(-1.5px 0 0.4em #42b883aa);
}
</style>

// examples/solid-mini/src/components/theme-toggle.tsx
import { createEffect, createSignal, onCleanup } from "solid-js";

export default function ThemeToggle() {
  const matchMedia = window.matchMedia("(prefers-color-scheme: dark)");

  const [isDarkMode, setIsDarkMode] = createSignal(matchMedia.matches);

  createEffect(() => {
    isDarkMode()
      ? document.body.classList.add("dark-scheme")
      : document.body.classList.remove("dark-scheme");
  });

  createEffect(() => {
    const handleChange = (e: MediaQueryListEvent) => setIsDarkMode(e.matches);

    matchMedia.addEventListener("change", handleChange);
    onCleanup(() => matchMedia.removeEventListener("change", handleChange));
  });

  const toggle = () => setIsDarkMode((s) => !s);

  return (
    <div class="centered">
      <div>
        <img src="logo.svg" role="button" onClick={toggle} alt="" />
      </div>
      <h1>Solid</h1>
      <p>Click the icon to switch between light and dark mode</p>
    </div>
  );
}
